### ISSUE TITLE
500 error - Uncaught Exception for ObjectExists validation

### ISSUE THREAD

**Issue by santiph** [zfcampus/zf-apigility-doctrine#217]
I have the ObjectExists validation set for a particular attribute (Location) of an endpoint (Create Venue).
In there, the service is expecting the client to send the Location Id, but if it doesn't, it just explode with a 500 error and the exception in the console.

I think `Zend\Validator\Exception\RuntimeException` from Doctrine should be captured and exposed back to the client instead.

```
[Sun Jul 26 18:30:10 2015] PHP Fatal error:  Uncaught exception 'Zend\Validator\Exception\RuntimeException' with message 'Field "id" was not provided, but was expected since the configured field lists needs it for validation' in /app/vendor/doctrine/doctrine-module/src/DoctrineModule/Validator/ObjectExists.php:148
Stack trace:
#0 /app/vendor/doctrine/doctrine-module/src/DoctrineModule/Validator/ObjectExists.php(182): DoctrineModule\Validator\ObjectExists->cleanSearchValue(Array)
#1 /app/vendor/zendframework/zend-validator/src/ValidatorChain.php(242): DoctrineModule\Validator\ObjectExists->isValid(Array, Array)
#2 /app/vendor/zendframework/zend-inputfilter/src/Input.php(346): Zend\Validator\ValidatorChain->isValid(Array, Array)
#3 /app/vendor/zendframework/zend-inputfilter/src/BaseInputFilter.php(267): Zend\InputFilter\Input->isValid(Array)
#4 /app/vendor/doctrine/doctrine-module/src/DoctrineModule/Validator/ObjectExists.php on line 148
```

**Comment by TomHAnderson** [comment]
@santiph I see where you mentioned this in another bug.  We haven't had any input here.  Can I close this?

**Comment by jguittard** [comment]
Closed due to inactivity
